server:
  port: 8987
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/datax?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#  activiti:
#    #自动检查、部署流程定义文件
#    check-process-definitions: true
#    #自动更新数据库结构
#    database-schema-update: true
#    #流程定义文件存放目录
#    process-definition-location-prefix: classpath:/processes/
#
#
#mybatis:
#  mapper-locations: classpath:/mapper/*Dao.xml
#  typeAliasesPackage: com.example.demo.entity


